[Export]
baked_notebookfile = true

# needs to be in both section to avoid running!
exclude=[
    "teca/generate/generate.jl"
       ]

slider_server_url="https://jupyter.ep3.uni-bayreuth.de"
cache_dir="My_pluto_state_cache"

[SliderServer]
port = 2346
host = "127.0.0.2"

exclude=[
    "teca/generate/generate.jl"
       ]

# You can also set Pluto's configuration here:
[Pluto]
[Pluto.compiler]
#threads = 1

